import Head from "next/head";
import Image from "next/image";
import { basePath } from "../../next.config";
import imghead from "../public/images/nombre.png";
import consejos from '../public/images/100consejos.png'
import fotoAgusto from '../public/images/foto.png'
import titulo from '../public/images/titulo.png'


export default function Home() {
  return (
    <div className='main'>
      <Head>
        <title>100 Consejos de poder </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className='flex flex-col'>
        <div className="m-auto text-center pt-2 w-[250px] md:w-[430px] lg:w-[1024px] ">
          <Image src={titulo}/>
        </div>
        <div className="text-center">
          <Image src={fotoAgusto} objectFit='cover'/>
        </div>
        <p className='font-bold text-justify px-7 text-[10px] md:text-[18px] lg:text-[32px]'>
          Bienvenidos a Las Voces del Poder, los verdaderos protagonistas en esta tercera edición de 100 Consejos de Poder. En las siguientes conversaciones encontrarán valiosas experiencias y consejos ofrecidos directamente por lideres políticos que han logrado ocupar la silla de la victoria.
        </p>
        <h1>Aqui vamos a crear un componente que llame los videos del backend</h1>
      </div>    
    </div>
  );
}
