import Head from "next/head";
import Image from "next/image";
import { basePath } from "../../next.config";
import imghead from "../public/images/nombre.png";
import consejos from '../public/images/100consejos.png'
import fotoAgusto from '../public/images/foto.png'
import titulo from '../public/images/titulo.png'
import footer from '../public/images/footer.png'
import Form from '../components/form'

export default function Home() {
  return (
    <div className="bg-[#ff5000]">
      <Head>
        <title>100 Consejos de poder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <div className='w-4/5 m-auto bg-white flex flex-col'>
        <div className="w-100 text-center">
          <Image src={imghead} width={200} height={35}/>
        </div>
        <div className="w-100 p-2 text-center">
          <Image src={consejos}/>
        </div>
        <div className="w-100 text-center">
          <Image src={fotoAgusto}/>
        </div>
        <p className='text-[10px] font-bold text-justify px-7'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam distinctio nemo ex cum quos? Officia repudiandae quos eligendi, distinctio nulla, pariatur explicabo quis, tempora quisquam magni tenetur. Delectus, veritatis quod?</p>
        <div className="w-100 text-center pt-2">
          <Image src={titulo}/>
        </div>
        <h1>Aqui vamos a crear un componente que llame los videos del backend</h1>
        <div className="w-100 text-center pt-2 px-2">
          <Image src={footer}/>
        </div>
        <p className='text-center font-bold'>¡ESCRIBEME!</p>
        <Form/>
      </div>
    </div>
  );
}
